# Generated by Django 4.2.16 on 2025-05-22 01:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_book_genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('biography', 'Biography')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_music_genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('hiphop', 'Hip-Hop'), ('classical', 'Classical')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
