# Generated by Django 4.2.16 on 2025-05-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_book_genres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_music_genres',
        ),
    ]
