# Generated by Django 4.2.16 on 2025-05-24 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('prompt', models.TextField(help_text='음악 생성을 위한 프롬프트')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='aisong/')),
                ('audio_url', models.URLField(blank=True, help_text='Suno API에서 제공하는 원본 오디오 URL', null=True)),
                ('title', models.CharField(blank=True, help_text='음악 제목', max_length=255, null=True)),
                ('duration', models.FloatField(blank=True, help_text='음악 길이(초)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '생성 대기중'), ('processing', '생성 중'), ('completed', '생성 완료'), ('failed', '생성 실패')], default='pending', max_length=20)),
                ('book', models.ForeignKey(blank=True, help_text='음악이 생성된 책', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
