# Generated by Django 4.2.16 on 2025-05-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdsong',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
