# Generated by Django 4.2.16 on 2025-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='recommended_song',
            field=models.URLField(blank=True, null=True),
        ),
    ]
