# Generated by Django 4.2.16 on 2025-05-23 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='like_books',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
