# Generated by Django 4.2.16 on 2025-05-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='main_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
