# Generated by Django 4.2.16 on 2025-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread_song',
            old_name='like_books',
            new_name='like_songs',
        ),
        migrations.RemoveField(
            model_name='thread_song',
            name='song',
        ),
        migrations.RemoveField(
            model_name='thread_song',
            name='title',
        ),
        migrations.AddField(
            model_name='thread_song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='user_song/'),
        ),
    ]
