# Generated by Django 4.2.16 on 2025-05-26 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_thread_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='like_books',
            field=models.ManyToManyField(related_name='liked_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
