# Generated by Django 4.2.16 on 2025-05-23 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_books_like_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='main_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='like_books',
            field=models.ManyToManyField(related_name='like_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread_song',
            name='like_books',
            field=models.ManyToManyField(related_name='like_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
