# Generated by Django 4.2.16 on 2025-05-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_like_books_thread_song_like_songs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread_song',
            old_name='like_songs',
            new_name='likesongs',
        ),
    ]
